### ISSUE TITLE
Add/Use version sub directory 

### ISSUE THREAD

**Issue by Pax-nl** [olivergregorius/micropython_ota#8]
Hi,

I tried your OTA solution and it works as advertised, thank you for this.

I would like to add this as an enhancement for easier use of your project.

I had to create a bash script to get the files uploaded with the correct names. 
Which is fine, but if you add a version dir I think you can make your project easier to use.

```
server-root/
|- <project_name>/
|  |- version <- version file
|  |  <version dir> |- <filename1>
|  |  <version dir> |- <filename2>
|  |  <version dir> |- ...
```
This way you can use filenames without versions and keep uploading/syncing with your webserver easy.

For now this is my bash script:

```
#!/usr/bin/env bash

echo "uploading version: ${1} for ${2}"

`echo "$1" > version`

scp version mm:/var/www/html/$2/version
scp boot.py mm:/var/www/html/$2/$1_boot.py
scp main.py mm:/var/www/html/$2/$1_main.py
scp config_$2.py mm:/var/www/html/$2/$1_config.py
```

usage: `./upload.sh 1.0.4 tuinhuis_monitor`

**Comment by olivergregorius** [comment]
Hey @Swieep, thank you very much for your proposal. I really appreciate that.

Nice idea, but implementing it this way only would be a breaking change. What about adding your proposed solution as another flavor of how this library can act? We could give the user the opportunity to choose by setting a config flag like `use_version_dirs` or something like that what directory structure he wants to use.

**Comment by Pax-nl** [comment]
Hi @olivergregorius ,

You are welcome and again thanks for creating this project I really needed it as I came from C++/PlatformIO where all my devices are responding to OTA updates which is handy with some of my devices tucked away in odd places.

I like your proposal and prevent breaking changes.. config flag sounds great. 
If you want me to test your new code let me know..

Kind regards, Swieep.

**Comment by olivergregorius** [comment]
Hey @Pax-IT, I just implemented the feature. If you want, you can test it. The py-file is available here: [micropython_ota.py](https://raw.githubusercontent.com/olivergregorius/micropython_ota/8-support_version_subdirectory_structure/micropython_ota.py)

Feel free to review and comment the corresponding pull request #12.

Kind regards
olivergregorius
